<a href="https://colab.research.google.com/github/sanjay-MGR/model_selection_and_predication/blob/main/Model_selection_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#import laiberis
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
#load datasets
data = sns.load_dataset('mpg')

In [ ]:
data.head(3)

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite

In [ ]:
#import the model(Rgression)
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.svm import SVR
from sklearn.ensemble import RandomForestRegressor
from sklearn.naive_bayes import GaussianNB

In [ ]:
#build the model
linear = LinearRegression()
tree = DecisionTreeRegressor()
svm = SVR()
forest = RandomForestRegressor()

In [ ]:
#split data into x and y
df = data[['mpg','cylinders','displacement','horsepower','weight','acceleration']]

In [ ]:
df.isna().sum()

mpg             0
cylinders       0
displacement    0
horsepower      6
weight          0
acceleration    0
dtype: int64

In [ ]:
df['horsepower'] = df['horsepower'].fillna(df['horsepower'].mean())

/tmp/ipykernel_524/2303749964.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['horsepower'] = df['horsepower'].fillna(df['horsepower'].mean())

In [ ]:
df.isna().sum()

mpg             0
cylinders       0
displacement    0
horsepower      0
weight          0
acceleration    0
dtype: int64

In [ ]:
x = df.drop('mpg',axis = 1)

In [ ]:
y = df['mpg']

In [ ]:
#train test split
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state = 42)

In [ ]:
#fit the model
linear.fit(x_train,y_train)

LinearRegression()

In [ ]:
tree.fit(x_train,y_train)

DecisionTreeRegressor()

In [ ]:
svm.fit(x_train,y_train)

SVR()

In [ ]:
forest.fit(x_train,y_train)

RandomForestRegressor()

In [ ]:
#predict the value
linear_test = linear.predict(x_test)
liner_train = linear.predict(x_train)

In [ ]:
tree_train = tree.predict(x_train)
tree_test = tree.predict(x_test)

In [ ]:
forest_train = forest.predict(x_train)
forest_test = forest.predict(x_test)

In [ ]:
svm_train = svm.predict(x_train)
svm_test = svm.predict(x_test)

In [ ]:
#check th accuracy
from sklearn.metrics import r2_score

In [ ]:
#linear regression
r2_train_linear = r2_score(y_train,liner_train)
r2_train_linear

0.6992557103754654

In [ ]:
r2_test_linear = r2_score(y_test,linear_test)
r2_test_linear

0.7272038917065151

In [ ]:
#decion tree regression
r2_tree_train = r2_score(y_train,tree_train)
r2_tree_train

0.9997742935245364

In [ ]:
r2_tree_test = r2_score(y_test,tree_test)
r2_tree_test

0.5959468678826281

In [ ]:
#random forest Regressor
r2_forest_train = r2_score(y_train,forest_train)
r2_forest_train

0.9650813097664351

In [ ]:
r2_forest_test = r2_score(y_test,forest_test)
r2_forest_test

0.753253935589411

In [ ]:
#svm
r2_svm_train = r2_score(y_train,svm_train)
r2_svm_train

0.6838587898691583

In [ ]:
r2_svm_test = r2_score(y_test,svm_test)
r2_svm_test

0.7452019563343675

In [ ]:
#after analizing the above model
#the best accuracy score is get from random forest Regressor model
#so we select the random forest Recursion model to get the output

In [ ]:
#save the model
import joblib
joblib.dump(forest,'forest_model.pkl')

['forest_model.pkl']

In [ ]:
#save the model and predict the mpg by importing model
x

     cylinders  displacement  horsepower  weight  acceleration
0            8         307.0       130.0    3504          12.0
1            8         350.0       165.0    3693          11.5
2            8         318.0       150.0    3436          11.0
3            8         304.0       150.0    3433          12.0
4            8         302.0       140.0    3449          10.5
..         ...           ...         ...     ...           ...
393          4         140.0        86.0    2790          15.6
394          4          97.0        52.0    2130          24.6
395          4         135.0        84.0    2295          11.6
396          4         120.0        79.0    2625          18.6
397          4         119.0        82.0    2720          19.4

[398 rows x 5 columns]

In [ ]:
x.to_csv('input data to get the input.csv')