<a href="https://colab.research.google.com/github/sanjay-MGR/model_selection_and_predication/blob/main/Predict_the_mpg_using_the_save_model_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#import laiberis
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import joblib

In [ ]:
from google.colab import files

In [ ]:
upload = files.upload()

Saving forest_model.pkl to forest_model.pkl

In [ ]:
model = joblib.load('/content/forest_model.pkl')

In [ ]:
model

RandomForestRegressor()

In [ ]:
upload = files.upload()

Saving expanded_1000_rows.csv to expanded_1000_rows.csv

In [ ]:
data = pd.read_csv(r"/content/expanded_1000_rows.csv")

In [ ]:
data.head(2)

   Unnamed: 0  cylinders  displacement  horsepower  weight  acceleration
0           0          8         307.0       130.0    3504          12.0
1           1          8         350.0       165.0    3693          11.5

In [ ]:
data.columns

Index(['Unnamed: 0', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration'],
      dtype='object')

In [ ]:
data= data.drop('Unnamed: 0',axis = 1)

In [ ]:
data.head(4)

   cylinders  displacement  horsepower  weight  acceleration
0          8         307.0       130.0    3504          12.0
1          8         350.0       165.0    3693          11.5
2          8         318.0       150.0    3436          11.0
3          8         304.0       150.0    3433          12.0

In [ ]:
#make a predication
mpg_output = model.predict(data)

In [ ]:
mpg_output

array([17.018     , 15.1515    , 16.99      , 16.23514286, 17.064     ,
       14.204     , 14.026     , 14.03      , 13.455     , 14.06      ,
       15.226     , 14.511     , 14.825     , 14.682     , 24.694     ,
       19.254     , 18.865     , 21.184     , 27.225     , 28.309     ,
       26.028     , 26.976     , 24.857     , 26.065     , 20.62      ,
       11.629     , 11.198     , 12.283     ,  9.895     , 27.225     ,
       25.317     , 25.286     , 24.989     , 21.674     , 16.82      ,
       17.685     , 18.726     , 18.612     , 14.154     , 14.155     ,
       14.225     , 14.405     , 12.79      , 12.94      , 12.66      ,
       21.655     , 24.931     , 18.959     , 18.594     , 24.133     ,
       26.902     , 32.284     , 30.513     , 32.13      , 34.449     ,
       32.2       , 33.118     , 25.975     , 26.837     , 25.763     ,
       21.779     , 22.059     , 13.681     , 13.885     , 14.89      ,
       14.055     , 15.86814286, 11.93      , 12.98      , 12.5       ,
       13.43      , 21.104     , 15.53614286, 15.608     , 13.928     ,
       14.175     , 21.642     , 30.262     , 22.582     , 28.783     ,
       23.389     , 27.03      , 24.883     , 28.855     , 27.421     ,
       13.595     , 15.86814286, 13.574     , 14.646     , 15.003     ,
       11.85      , 13.1       , 13.455     , 15.427     , 11.78      ,
       12.06      , 13.57      , 19.102     , 16.472     , 18.625     ,
       19.082     , 19.502     , 27.969     , 11.829     , 12.33      ,
       13.02      , 12.525     , 18.629     , 22.573     , 24.342     ,
       23.633     , 21.711     , 21.696     , 24.532     , 26.662     ,
       14.63      , 14.17      , 32.374     , 27.036     , 22.835     ,
       20.352     , 15.709     , 24.247     , 21.954     , 14.7245    ,
       19.83      , 19.602     , 19.135     , 15.955     , 31.661     ,
       26.727     , 31.815     , 28.364     , 16.326     , 16.534     ,
       18.268     , 15.749     , 12.889     , 13.46      , 13.77      ,
       14.068     , 26.919     , 28.451     , 27.314     , 32.832     ,
       32.791     , 29.402     , 27.508     , 30.726     , 24.638     ,
       26.662     , 31.875     , 20.155     , 18.077     , 17.304     ,
       17.481     , 14.71      , 14.552     , 13.353     , 13.68      ,
       17.247     , 16.132     , 15.525     , 17.623     , 20.882     ,
       20.933     , 15.038     , 29.286     , 26.306     , 19.585     ,
       24.723     , 25.242     , 32.188     , 25.31      , 19.461     ,
       32.513     , 19.292     , 24.105     , 23.57      , 22.391     ,
       24.335     , 35.766     , 27.166     , 26.11      , 25.835     ,
       27.022     , 28.012     , 16.889     , 15.4       , 16.274     ,
       14.47      , 20.885     , 20.57      , 23.206     , 21.228     ,
       31.893     , 31.341     , 30.715     , 35.741     , 19.422     ,
       18.534     , 18.268     , 17.734     , 31.42      , 32.787     ,
       28.405     , 27.796     , 20.795     , 14.291     , 21.082     ,
       20.198     , 17.519     , 14.899     , 13.72      , 14.058     ,
       13.674     , 31.85      , 29.989     , 35.565     , 25.038     ,
       33.195     , 16.266     , 16.777     , 15.359     , 14.754     ,
       18.244     , 20.315     , 18.896     , 17.828     , 14.35      ,
       14.98      , 15.02      , 15.599     , 30.017     , 26.887     ,
       27.294     , 25.481     , 31.648     , 28.423     , 30.936     ,
       30.134     , 22.63      , 23.265     , 21.904     , 39.922     ,
       34.879     , 32.872     , 36.634     , 36.17      , 19.372     ,
       18.353     , 19.038     , 18.821     , 20.164     , 20.531     ,
       25.626     , 19.721     , 19.48      , 20.67      , 20.672     ,
       18.701     , 19.455     , 17.458     , 17.645     , 17.208     ,
       16.942     , 30.503     , 25.564     , 27.135     , 31.572     ,
       23.511     , 24.355     , 25.966     , 24.877     , 21.372     ,
       20.076     , 22.102     , 17.611     , 31.475     , 30.892     ,
       21.537     , 20.732     , 23.704     , 19.858     , 20.342     ,
       15.6       , 17.281     , 16.645     , 16.493     , 15.28      ,
       15.555     , 19.109     , 13.967     , 32.51      , 32.412     ,
       33.835     , 27.997     , 24.779     , 18.088     , 28.232     ,
       21.786     , 33.94      , 34.41      , 32.336     , 36.975     ,
       27.875     , 28.182     , 24.862     , 31.224     , 36.616     ,
       37.098     , 32.346     , 35.936     , 27.521     , 25.378     ,
       24.509     , 19.592     , 31.677     , 24.858     , 30.936     ,
       32.52      , 31.689     , 43.76      , 25.998     , 40.135     ,
       42.613     , 39.222     , 33.619     , 30.456     , 40.094     ,
       35.804     , 33.034     , 31.56      , 27.054     , 23.1       ,
       31.137     , 23.875     , 30.294     , 27.525     , 26.859     ,
       26.176     , 24.575     , 31.187     , 36.805     , 36.976     ,
       35.042     , 32.131     , 35.113     , 36.385     , 34.274     ,
       35.19      , 32.3       , 30.07      , 33.146     , 30.992     ,
       33.82      , 31.55      , 28.557     , 30.668     , 26.932     ,
       28.396     , 24.685     , 22.884     , 21.676     , 22.44      ,
       20.431     , 18.02      , 25.147     , 26.411     , 31.014     ,
       26.397     , 28.06      , 26.997     , 24.774     , 23.044     ,
       30.024     , 36.036     , 35.041     , 37.039     , 34.393     ,
       26.478     , 34.647     , 32.802     , 32.207     , 32.38      ,
       36.766     , 20.101     , 31.026     , 26.46      , 19.791     ,
       29.163     , 33.357     , 26.319     , 24.912     , 29.216     ,
       31.486     , 27.728     , 28.963     , 17.018     , 15.1515    ,
       16.99      , 16.23514286, 17.064     , 14.204     , 14.026     ,
       14.03      , 13.455     , 14.06      , 15.226     , 14.511     ,
       14.825     , 14.682     , 24.694     , 19.254     , 18.865     ,
       21.184     , 27.225     , 28.309     , 26.028     , 26.976     ,
       24.857     , 26.065     , 20.62      , 11.629     , 11.198     ,
       12.283     ,  9.895     , 27.225     , 25.317     , 25.286     ,
       24.989     , 21.674     , 16.82      , 17.685     , 18.726     ,
       18.612     , 14.154     , 14.155     , 14.225     , 14.405     ,
       12.79      , 12.94      , 12.66      , 21.655     , 24.931     ,
       18.959     , 18.594     , 24.133     , 26.902     , 32.284     ,
       30.513     , 32.13      , 34.449     , 32.2       , 33.118     ,
       25.975     , 26.837     , 25.763     , 21.779     , 22.059     ,
       13.681     , 13.885     , 14.89      , 14.055     , 15.86814286,
       11.93      , 12.98      , 12.5       , 13.43      , 21.104     ,
       15.53614286, 15.608     , 13.928     , 14.175     , 21.642     ,
       30.262     , 22.582     , 28.783     , 23.389     , 27.03      ,
       24.883     , 28.855     , 27.421     , 13.595     , 15.86814286,
       13.574     , 14.646     , 15.003     , 11.85      , 13.1       ,
       13.455     , 15.427     , 11.78      , 12.06      , 13.57      ,
       19.102     , 16.472     , 18.625     , 19.082     , 19.502     ,
       27.969     , 11.829     , 12.33      , 13.02      , 12.525     ,
       18.629     , 22.573     , 24.342     , 23.633     , 21.711     ,
       21.696     , 24.532     , 26.662     , 14.63      , 14.17      ,
       32.374     , 27.036     , 22.835     , 20.352     , 15.709     ,
       24.247     , 21.954     , 14.7245    , 19.83      , 19.602     ,
       19.135     , 15.955     , 31.661     , 26.727     , 31.815     ,
       28.364     , 16.326     , 16.534     , 18.268     , 15.749     ,
       12.889     , 13.46      , 13.77      , 14.068     , 26.919     ,
       28.451     , 27.314     , 32.832     , 32.791     , 29.402     ,
       27.508     , 30.726     , 24.638     , 26.662     , 31.875     ,
       20.155     , 18.077     , 17.304     , 17.481     , 14.71      ,
       14.552     , 13.353     , 13.68      , 17.247     , 16.132     ,
       15.525     , 17.623     , 20.882     , 20.933     , 15.038     ,
       29.286     , 26.306     , 19.585     , 24.723     , 25.242     ,
       32.188     , 25.31      , 19.461     , 32.513     , 19.292     ,
       24.105     , 23.57      , 22.391     , 24.335     , 35.766     ,
       27.166     , 26.11      , 25.835     , 27.022     , 28.012     ,
       16.889     , 15.4       , 16.274     , 14.47      , 20.885     ,
       20.57      , 23.206     , 21.228     , 31.893     , 31.341     ,
       30.715     , 35.741     , 19.422     , 18.534     , 18.268     ,
       17.734     , 31.42      , 32.787     , 28.405     , 27.796     ,
       20.795     , 14.291     , 21.082     , 20.198     , 17.519     ,
       14.899     , 13.72      , 14.058     , 13.674     , 31.85      ,
       29.989     , 35.565     , 25.038     , 33.195     , 16.266     ,
       16.777     , 15.359     , 14.754     , 18.244     , 20.315     ,
       18.896     , 17.828     , 14.35      , 14.98      , 15.02      ,
       15.599     , 30.017     , 26.887     , 27.294     , 25.481     ,
       31.648     , 28.423     , 30.936     , 30.134     , 22.63      ,
       23.265     , 21.904     , 39.922     , 34.879     , 32.872     ,
       36.634     , 36.17      , 19.372     , 18.353     , 19.038     ,
       18.821     , 20.164     , 20.531     , 25.626     , 19.721     ,
       19.48      , 20.67      , 20.672     , 18.701     , 19.455     ,
       17.458     , 17.645     , 17.208     , 16.942     , 30.503     ,
       25.564     , 27.135     , 31.572     , 23.511     , 24.355     ,
       25.966     , 24.877     , 21.372     , 20.076     , 22.102     ,
       17.611     , 31.475     , 30.892     , 21.537     , 20.732     ,
       23.704     , 19.858     , 20.342     , 15.6       , 17.281     ,
       16.645     , 16.493     , 15.28      , 15.555     , 19.109     ,
       13.967     , 32.51      , 32.412     , 33.835     , 27.997     ,
       24.779     , 18.088     , 28.232     , 21.786     , 33.94      ,
       34.41      , 32.336     , 36.975     , 27.875     , 28.182     ,
       24.862     , 31.224     , 36.616     , 37.098     , 32.346     ,
       35.936     , 27.521     , 25.378     , 24.509     , 19.592     ,
       31.677     , 24.858     , 30.936     , 32.52      , 31.689     ,
       43.76      , 25.998     , 40.135     , 42.613     , 39.222     ,
       33.619     , 30.456     , 40.094     , 35.804     , 33.034     ,
       31.56      , 27.054     , 23.1       , 31.137     , 23.875     ,
       30.294     , 27.525     , 26.859     , 26.176     , 24.575     ,
       31.187     , 36.805     , 36.976     , 35.042     , 32.131     ,
       35.113     , 36.385     , 34.274     , 35.19      , 32.3       ,
       30.07      , 33.146     , 30.992     , 33.82      , 31.55      ,
       28.557     , 30.668     , 26.932     , 28.396     , 24.685     ,
       22.884     , 21.676     , 22.44      , 20.431     , 18.02      ,
       25.147     , 26.411     , 31.014     , 26.397     , 28.06      ,
       26.997     , 24.774     , 23.044     , 30.024     , 36.036     ,
       35.041     , 37.039     , 34.393     , 26.478     , 34.647     ,
       32.802     , 32.207     , 32.38      , 36.766     , 20.101     ,
       31.026     , 26.46      , 19.791     , 29.163     , 33.357     ,
       26.319     , 24.912     , 29.216     , 31.486     , 27.728     ,
       28.963     , 17.018     , 15.1515    , 16.99      , 16.23514286,
       17.064     , 14.204     , 14.026     , 14.03      , 13.455     ,
       14.06      , 15.226     , 14.511     , 14.825     , 14.682     ,
       24.694     , 19.254     , 18.865     , 21.184     , 27.225     ,
       28.309     , 26.028     , 26.976     , 24.857     , 26.065     ,
       20.62      , 11.629     , 11.198     , 12.283     ,  9.895     ,
       27.225     , 25.317     , 25.286     , 24.989     , 21.674     ,
       16.82      , 17.685     , 18.726     , 18.612     , 14.154     ,
       14.155     , 14.225     , 14.405     , 12.79      , 12.94      ,
       12.66      , 21.655     , 24.931     , 18.959     , 18.594     ,
       24.133     , 26.902     , 32.284     , 30.513     , 32.13      ,
       34.449     , 32.2       , 33.118     , 25.975     , 26.837     ,
       25.763     , 21.779     , 22.059     , 13.681     , 13.885     ,
       14.89      , 14.055     , 15.86814286, 11.93      , 12.98      ,
       12.5       , 13.43      , 21.104     , 15.53614286, 15.608     ,
       13.928     , 14.175     , 21.642     , 30.262     , 22.582     ,
       28.783     , 23.389     , 27.03      , 24.883     , 28.855     ,
       27.421     , 13.595     , 15.86814286, 13.574     , 14.646     ,
       15.003     , 11.85      , 13.1       , 13.455     , 15.427     ,
       11.78      , 12.06      , 13.57      , 19.102     , 16.472     ,
       18.625     , 19.082     , 19.502     , 27.969     , 11.829     ,
       12.33      , 13.02      , 12.525     , 18.629     , 22.573     ,
       24.342     , 23.633     , 21.711     , 21.696     , 24.532     ,
       26.662     , 14.63      , 14.17      , 32.374     , 27.036     ,
       22.835     , 20.352     , 15.709     , 24.247     , 21.954     ,
       14.7245    , 19.83      , 19.602     , 19.135     , 15.955     ,
       31.661     , 26.727     , 31.815     , 28.364     , 16.326     ,
       16.534     , 18.268     , 15.749     , 12.889     , 13.46      ,
       13.77      , 14.068     , 26.919     , 28.451     , 27.314     ,
       32.832     , 32.791     , 29.402     , 27.508     , 30.726     ,
       24.638     , 26.662     , 31.875     , 20.155     , 18.077     ,
       17.304     , 17.481     , 14.71      , 14.552     , 13.353     ,
       13.68      , 17.247     , 16.132     , 15.525     , 17.623     ,
       20.882     , 20.933     , 15.038     , 29.286     , 26.306     ,
       19.585     , 24.723     , 25.242     , 32.188     , 25.31      ,
       19.461     , 32.513     , 19.292     , 24.105     , 23.57      ,
       22.391     , 24.335     , 35.766     , 27.166     , 26.11      ,
       25.835     , 27.022     , 28.012     , 16.889     , 15.4       ,
       16.274     , 14.47      , 20.885     , 20.57      , 23.206     ,
       21.228     , 31.893     , 31.341     , 30.715     , 35.741     ,
       19.422     , 18.534     , 18.268     , 17.734     , 31.42      ])

In [ ]:
output_mpg = pd.DataFrame(mpg_output,columns = ['output_mpg'])

In [ ]:
output_mpg

     output_mpg
0     17.018000
1     15.151500
2     16.990000
3     16.235143
4     17.064000
..          ...
995   19.422000
996   18.534000
997   18.268000
998   17.734000
999   31.420000

[1000 rows x 1 columns]

In [ ]:
#save the output
output_mpg.to_csv('output_mpg.csv')

In [ ]:
#put the output into the Dataset
data['output_mpg']=mpg_output

In [ ]:
data.head(2)

   cylinders  displacement  horsepower  weight  acceleration  output_mpg
0          8         307.0       130.0    3504          12.0     17.0180
1          8         350.0       165.0    3693          11.5     15.1515

In [ ]:
#save the input output
data.to_csv('input with predicted ')